'use cliente';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { SidebarProvider } from "@/components/ui/sidebar";
import Menu from "@/components/ui/menu";
import { ModeToggle } from "@/components/providers/modo";
import { ThemeProvider } from "@/components/providers/theme-provider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly <{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <ThemeProvider attribute={"class"} defaultTheme="system" enableSystem>
      <SidebarProvider>
          <div className="flex">
            <Menu />
            <main className="flex-1 p-6  min-h-screen">

              <div className="flex justify-end m-2">

                <ModeToggle />
              
              </div>
              
              {children}
              
              </main>
          </div>
        </SidebarProvider>
        </ThemeProvider>
      
      </body>
      
      
      
    </html>
  );
}
